//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appRegistroSena.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.ServicioSoap")]
    public interface ServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        appRegistroSena.WebService.HelloWorldResponse HelloWorld(appRegistroSena.WebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<appRegistroSena.WebService.HelloWorldResponse> HelloWorldAsync(appRegistroSena.WebService.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoVehiculo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrar", ReplyAction="*")]
        appRegistroSena.WebService.mtdRegistrarResponse mtdRegistrar(appRegistroSena.WebService.mtdRegistrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrar", ReplyAction="*")]
        System.Threading.Tasks.Task<appRegistroSena.WebService.mtdRegistrarResponse> mtdRegistrarAsync(appRegistroSena.WebService.mtdRegistrarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public appRegistroSena.WebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(appRegistroSena.WebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public appRegistroSena.WebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(appRegistroSena.WebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdRegistrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdRegistrar", Namespace="http://tempuri.org/", Order=0)]
        public appRegistroSena.WebService.mtdRegistrarRequestBody Body;
        
        public mtdRegistrarRequest() {
        }
        
        public mtdRegistrarRequest(appRegistroSena.WebService.mtdRegistrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdRegistrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipoVehiculo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string placa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string color;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string marca;
        
        public mtdRegistrarRequestBody() {
        }
        
        public mtdRegistrarRequestBody(string tipoVehiculo, string placa, string color, string marca) {
            this.tipoVehiculo = tipoVehiculo;
            this.placa = placa;
            this.color = color;
            this.marca = marca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdRegistrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdRegistrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public appRegistroSena.WebService.mtdRegistrarResponseBody Body;
        
        public mtdRegistrarResponse() {
        }
        
        public mtdRegistrarResponse(appRegistroSena.WebService.mtdRegistrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdRegistrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mtdRegistrarResult;
        
        public mtdRegistrarResponseBody() {
        }
        
        public mtdRegistrarResponseBody(string mtdRegistrarResult) {
            this.mtdRegistrarResult = mtdRegistrarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSoapChannel : appRegistroSena.WebService.ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoapClient : System.ServiceModel.ClientBase<appRegistroSena.WebService.ServicioSoap>, appRegistroSena.WebService.ServicioSoap {
        
        public ServicioSoapClient() {
        }
        
        public ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        appRegistroSena.WebService.HelloWorldResponse appRegistroSena.WebService.ServicioSoap.HelloWorld(appRegistroSena.WebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            appRegistroSena.WebService.HelloWorldRequest inValue = new appRegistroSena.WebService.HelloWorldRequest();
            inValue.Body = new appRegistroSena.WebService.HelloWorldRequestBody();
            appRegistroSena.WebService.HelloWorldResponse retVal = ((appRegistroSena.WebService.ServicioSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<appRegistroSena.WebService.HelloWorldResponse> appRegistroSena.WebService.ServicioSoap.HelloWorldAsync(appRegistroSena.WebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<appRegistroSena.WebService.HelloWorldResponse> HelloWorldAsync() {
            appRegistroSena.WebService.HelloWorldRequest inValue = new appRegistroSena.WebService.HelloWorldRequest();
            inValue.Body = new appRegistroSena.WebService.HelloWorldRequestBody();
            return ((appRegistroSena.WebService.ServicioSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        appRegistroSena.WebService.mtdRegistrarResponse appRegistroSena.WebService.ServicioSoap.mtdRegistrar(appRegistroSena.WebService.mtdRegistrarRequest request) {
            return base.Channel.mtdRegistrar(request);
        }
        
        public string mtdRegistrar(string tipoVehiculo, string placa, string color, string marca) {
            appRegistroSena.WebService.mtdRegistrarRequest inValue = new appRegistroSena.WebService.mtdRegistrarRequest();
            inValue.Body = new appRegistroSena.WebService.mtdRegistrarRequestBody();
            inValue.Body.tipoVehiculo = tipoVehiculo;
            inValue.Body.placa = placa;
            inValue.Body.color = color;
            inValue.Body.marca = marca;
            appRegistroSena.WebService.mtdRegistrarResponse retVal = ((appRegistroSena.WebService.ServicioSoap)(this)).mtdRegistrar(inValue);
            return retVal.Body.mtdRegistrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<appRegistroSena.WebService.mtdRegistrarResponse> appRegistroSena.WebService.ServicioSoap.mtdRegistrarAsync(appRegistroSena.WebService.mtdRegistrarRequest request) {
            return base.Channel.mtdRegistrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<appRegistroSena.WebService.mtdRegistrarResponse> mtdRegistrarAsync(string tipoVehiculo, string placa, string color, string marca) {
            appRegistroSena.WebService.mtdRegistrarRequest inValue = new appRegistroSena.WebService.mtdRegistrarRequest();
            inValue.Body = new appRegistroSena.WebService.mtdRegistrarRequestBody();
            inValue.Body.tipoVehiculo = tipoVehiculo;
            inValue.Body.placa = placa;
            inValue.Body.color = color;
            inValue.Body.marca = marca;
            return ((appRegistroSena.WebService.ServicioSoap)(this)).mtdRegistrarAsync(inValue);
        }
    }
}
